targets:
  $default:
    builders:
      pg_dorm:modelFromYamlGen:
        generate_for:
          include:
            - lib/models/**
            - test/models/**
        enabled: true
builders:
  modelFromYamlGen:
    import: "package:pg_dorm/generators/builders.dart"
    builder_factories: ["modelFromYamlBuilder"]
    build_extensions: { ".yml": [".dart"], "yaml": [".dart"] }
    auto_apply: dependents
    build_to: source
