/// Main code generator for Gisila ORM
///
/// Coordinates the generation of models, migrations, and other
/// database artifacts from schema definitions.
library gisila.generators.code_generator;

import 'dart:io';
import 'schema_parser.dart';
import 'model_generator.dart';
import 'query_generator.dart';

/// Main code generator class
class CodeGenerator {
  final SchemaDefinition schema;
  final String outputDirectory;

  CodeGenerator({
    required this.schema,
    required this.outputDirectory,
  });

  /// Generate all code artifacts
  Future<void> generateAll() async {
    print('🚀 Starting code generation...');

    // Create base output directory
    final dir = Directory(outputDirectory);
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }

    // Generate models and queries using part of approach
    await _generateModelsWithPartOf();

    // Generate migrations
    await _generateMigrations();

    // Generate database setup
    await _generateDatabaseSetup();

    print('✅ Code generation completed successfully!');
  }

  /// Generate all models and queries as parts of a single library
  Future<void> _generateModelsWithPartOf() async {
    print('📦 Generating models and queries with part of approach...');

    // Create the parts directory
    final partsDir = '$outputDirectory/generated';
    final dir = Directory(partsDir);
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }

    // Generate the main library file
    await _generateMainLibraryFile();

    // Generate base model as part
    await _generateBaseModelPart();

    // Generate database context as part
    await _generateDatabaseContextPart();

    final modelGenerator = ModelGenerator(
      schema: schema,
      outputDirectory: partsDir,
    );
    final queryGenerator = QueryGenerator();

    // Generate each model as a part
    for (final model in schema.models) {
      await _generateModelPart(model, modelGenerator, partsDir);
      await _generateQueryPart(model, queryGenerator, partsDir);
    }

    print('   Generated ${schema.models.length} models and queries as parts');
  }

  /// Generate the main library file that includes all parts
  Future<void> _generateMainLibraryFile() async {
    final mainFile = File('$outputDirectory/models.dart');
    final buffer = StringBuffer();

    // Library declaration
    buffer.writeln('/// Generated models and queries library');
    buffer.writeln('/// DO NOT EDIT - This file is automatically generated');
    buffer.writeln();
    buffer.writeln('library gisila.generated.models;');
    buffer.writeln();

    // Common imports
    buffer.writeln("import 'dart:async';");
    buffer.writeln("import 'package:gisila/config/config.dart';");
    buffer
        .writeln("import 'package:gisila/database/postgres/query/query.dart';");
    buffer.writeln(
        "import 'package:gisila/database/postgres/query/operator.dart';");
    buffer.writeln();

    // Part declarations
    buffer.writeln('// Base classes');
    buffer.writeln("part 'generated/base_model.dart';");
    buffer.writeln("part 'generated/database_context.dart';");
    buffer.writeln();

    buffer.writeln('// Generated models');
    for (final model in schema.models) {
      final fileName = _toSnakeCase(model.name);
      buffer.writeln("part 'generated/${fileName}.dart';");
    }
    buffer.writeln();

    buffer.writeln('// Generated query builders');
    for (final model in schema.models) {
      final fileName = _toSnakeCase(model.name);
      buffer.writeln("part 'generated/${fileName}_query.dart';");
    }

    await mainFile.writeAsString(buffer.toString());
  }

  /// Generate base model as a part
  Future<void> _generateBaseModelPart() async {
    final file = File('$outputDirectory/generated/base_model.dart');
    final content = '''part of '../models.dart';

/// Base model class for all generated models
abstract class BaseModel {
  /// Convert model to map for database operations
  Map<String, dynamic> toMap();
  
  /// Validate model instance
  List<String> validate();
}

/// Validation exception for model validation errors
class ValidationException implements Exception {
  final List<String> errors;
  ValidationException(this.errors);

  @override
  String toString() => 'ValidationException: \${errors.join(", ")}';
}
''';

    await file.writeAsString(content);
  }

  /// Generate database context as a part
  Future<void> _generateDatabaseContextPart() async {
    final file = File('$outputDirectory/generated/database_context.dart');
    final content = '''part of '../models.dart';

/// Database context for executing queries
class DatabaseContext {
  static DatabaseContext? _instance;
  static DatabaseContext get instance => _instance ??= DatabaseContext._();
  
  DatabaseContext._();

  /// Execute a query and return results
  Future<List<Map<String, dynamic>>> query({
    required String sql,
    List<dynamic> parameters = const [],
    String? connectionName,
  }) async {
    // TODO: Implement actual database query execution
    print('Executing query: \$sql with parameters: \$parameters');
    return [];
  }

  /// Execute an insert statement
  Future<Map<String, dynamic>> insert({
    required String tableName,
    required Map<String, dynamic> data,
    String? connectionName,
  }) async {
    // TODO: Implement actual database insert
    print('Inserting into \$tableName: \$data');
    return {'id': 1, ...data};
  }

  /// Execute an update statement
  Future<int> update({
    required String tableName,
    required Map<String, dynamic> data,
    String? where,
    List<dynamic> parameters = const [],
    String? connectionName,
  }) async {
    // TODO: Implement actual database update
    print('Updating \$tableName: \$data where \$where with parameters: \$parameters');
    return 1;
  }

  /// Execute a delete statement
  Future<int> delete({
    required String tableName,
    String? where,
    List<dynamic> parameters = const [],
    String? connectionName,
  }) async {
    // TODO: Implement actual database delete
    print('Deleting from \$tableName where \$where with parameters: \$parameters');
    return 1;
  }
}
''';

    await file.writeAsString(content);
  }

  /// Generate a model as a part
  Future<void> _generateModelPart(ModelDefinition model,
      ModelGenerator modelGenerator, String partsDir) async {
    final fileName = '${_toSnakeCase(model.name)}.dart';
    final file = File('$partsDir/$fileName');

    final modelContent = modelGenerator.generateModelClassAsPart(model);
    await file.writeAsString(modelContent);
  }

  /// Generate a query builder as a part
  Future<void> _generateQueryPart(ModelDefinition model,
      QueryGenerator queryGenerator, String partsDir) async {
    final fileName = '${_toSnakeCase(model.name)}_query.dart';
    final file = File('$partsDir/$fileName');

    final buffer = StringBuffer();
    buffer.writeln("part of '../models.dart';");
    buffer.writeln();
    buffer.writeln('/// Generated query builder for ${model.name} model');
    buffer.writeln();
    buffer.writeln(queryGenerator.generateQueryClass(model));

    await file.writeAsString(buffer.toString());
  }

  /// Generate migration files
  Future<void> _generateMigrations() async {
    print('🔄 Generating migration files...');

    final migrationsDir = '$outputDirectory/migrations';
    final dir = Directory(migrationsDir);
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }

    // Generate initial migration
    final migrationContent = _generateInitialMigration();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final migrationFile =
        File('$migrationsDir/${timestamp}_initial_migration.sql');
    await migrationFile.writeAsString(migrationContent);

    // Generate down migration
    final downMigrationContent = _generateDownMigration();
    final downMigrationFile =
        File('$migrationsDir/${timestamp}_initial_migration.down.sql');
    await downMigrationFile.writeAsString(downMigrationContent);

    print('   Generated initial migration files');
  }

  /// Generate database setup files
  Future<void> _generateDatabaseSetup() async {
    print('🛠️  Generating database setup...');

    // Generate table creation SQL
    final setupContent = _generateTableCreationSQL();
    final setupFile = File('$outputDirectory/setup.sql');
    await setupFile.writeAsString(setupContent);

    // Generate drop SQL
    final dropContent = _generateDropSQL();
    final dropFile = File('$outputDirectory/drop.sql');
    await dropFile.writeAsString(dropContent);

    print('   Generated database setup files');
  }

  /// Generate initial migration SQL
  String _generateInitialMigration() {
    final buffer = StringBuffer();

    buffer.writeln('-- Initial migration for Gisila ORM');
    buffer.writeln('-- Generated on: ${DateTime.now().toIso8601String()}');
    buffer.writeln();
    buffer.writeln('BEGIN;');
    buffer.writeln();

    // Create tables
    for (final model in schema.models) {
      buffer.writeln(_generateCreateTableSQL(model));
      buffer.writeln();
    }

    // Create foreign key constraints
    for (final model in schema.models) {
      final foreignKeys = _generateForeignKeyConstraints(model);
      if (foreignKeys.isNotEmpty) {
        buffer.writeln(foreignKeys);
        buffer.writeln();
      }
    }

    // Create junction tables for many-to-many relationships
    for (final relationship
        in schema.relationships.where((r) => r.isManyToMany)) {
      buffer.writeln(_generateJunctionTableSQL(relationship));
      buffer.writeln();
    }

    // Create indexes
    for (final model in schema.models) {
      final indexes = _generateIndexes(model);
      if (indexes.isNotEmpty) {
        buffer.writeln(indexes);
        buffer.writeln();
      }
    }

    buffer.writeln('COMMIT;');

    return buffer.toString();
  }

  /// Generate down migration SQL
  String _generateDownMigration() {
    final buffer = StringBuffer();

    buffer.writeln('-- Down migration for Gisila ORM');
    buffer.writeln('-- Generated on: ${DateTime.now().toIso8601String()}');
    buffer.writeln();
    buffer.writeln('BEGIN;');
    buffer.writeln();

    // Drop junction tables first
    for (final relationship
        in schema.relationships.where((r) => r.isManyToMany)) {
      buffer.writeln('DROP TABLE IF EXISTS ${relationship.junctionTableName};');
    }
    buffer.writeln();

    // Drop tables in reverse order
    for (final model in schema.models.reversed) {
      buffer.writeln('DROP TABLE IF EXISTS ${model.tableName};');
    }
    buffer.writeln();

    buffer.writeln('COMMIT;');

    return buffer.toString();
  }

  /// Generate table creation SQL
  String _generateTableCreationSQL() {
    final buffer = StringBuffer();

    buffer.writeln('-- Table creation SQL for Gisila ORM');
    buffer.writeln('-- Generated on: ${DateTime.now().toIso8601String()}');
    buffer.writeln();

    for (final model in schema.models) {
      buffer.writeln(_generateCreateTableSQL(model));
      buffer.writeln();
    }

    return buffer.toString();
  }

  /// Generate drop SQL
  String _generateDropSQL() {
    final buffer = StringBuffer();

    buffer.writeln('-- Drop SQL for Gisila ORM');
    buffer.writeln('-- Generated on: ${DateTime.now().toIso8601String()}');
    buffer.writeln();

    for (final model in schema.models.reversed) {
      buffer.writeln('DROP TABLE IF EXISTS ${model.tableName};');
    }

    return buffer.toString();
  }

  /// Generate CREATE TABLE SQL for a model
  String _generateCreateTableSQL(ModelDefinition model) {
    final buffer = StringBuffer();

    buffer.writeln('CREATE TABLE ${model.tableName} (');

    final columnDefinitions = <String>[];

    // Add columns
    for (final column in model.columns
        .where((c) => !c.isRelationship || c.type == ColumnType.foreignKey)) {
      columnDefinitions.add(_generateColumnDefinition(column));
    }

    buffer.writeln('  ${columnDefinitions.join(',\n  ')}');
    buffer.writeln(');');

    return buffer.toString();
  }

  /// Generate column definition SQL
  String _generateColumnDefinition(ColumnDefinition column) {
    final buffer = StringBuffer();

    if (column.type == ColumnType.foreignKey) {
      buffer.write('${column.name}_id INTEGER');
    } else {
      buffer.write('${column.name} ${column.postgresType}');
    }

    // Add constraints
    if (column.constraints.isPrimary) {
      buffer.write(' PRIMARY KEY');
    }

    if (!column.constraints.isNull) {
      buffer.write(' NOT NULL');
    }

    if (column.constraints.isUnique && !column.constraints.isPrimary) {
      buffer.write(' UNIQUE');
    }

    if (column.constraints.defaultValue != null) {
      buffer.write(
          ' DEFAULT ${_formatDefaultValue(column.constraints.defaultValue)}');
    }

    return buffer.toString();
  }

  /// Format default value for SQL
  String _formatDefaultValue(dynamic value) {
    if (value is String) {
      if (value.toUpperCase() == 'NOW()' ||
          value.toUpperCase() == 'CURRENT_TIMESTAMP') {
        return 'CURRENT_TIMESTAMP';
      }
      return "'$value'";
    }
    return value.toString();
  }

  /// Generate foreign key constraints
  String _generateForeignKeyConstraints(ModelDefinition model) {
    final buffer = StringBuffer();

    for (final column in model.foreignKeyColumns) {
      final refModel = schema.getModel(column.relationship!.references!);
      if (refModel != null) {
        final constraintName = '${model.tableName}_${column.name}_fkey';
        buffer.writeln('ALTER TABLE ${model.tableName}');
        buffer.writeln('  ADD CONSTRAINT $constraintName');
        buffer.writeln('  FOREIGN KEY (${column.name}_id)');
        buffer.writeln(
            '  REFERENCES ${refModel.tableName} (${refModel.primaryKey?.name ?? 'id'})');
        buffer.writeln(
            '  ON DELETE ${column.relationship!.onDelete ?? 'SET NULL'}');
        buffer.writeln(
            '  ON UPDATE ${column.relationship!.onUpdate ?? 'CASCADE'};');
        buffer.writeln();
      }
    }

    return buffer.toString().trim();
  }

  /// Generate junction table for many-to-many relationships
  String _generateJunctionTableSQL(RelationshipInfo relationship) {
    final buffer = StringBuffer();

    final tableName = relationship.junctionTableName;
    final leftTable = _toSnakeCase(relationship.fromModel);
    final rightTable = _toSnakeCase(relationship.toModel);

    buffer.writeln('CREATE TABLE $tableName (');
    buffer.writeln('  ${leftTable}_id INTEGER NOT NULL,');
    buffer.writeln('  ${rightTable}_id INTEGER NOT NULL,');
    buffer.writeln('  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,');
    buffer.writeln('  PRIMARY KEY (${leftTable}_id, ${rightTable}_id),');
    buffer.writeln(
        '  FOREIGN KEY (${leftTable}_id) REFERENCES $leftTable (id) ON DELETE CASCADE,');
    buffer.writeln(
        '  FOREIGN KEY (${rightTable}_id) REFERENCES $rightTable (id) ON DELETE CASCADE');
    buffer.writeln(');');

    return buffer.toString();
  }

  /// Generate indexes
  String _generateIndexes(ModelDefinition model) {
    final buffer = StringBuffer();

    // Generate indexes for indexed columns
    for (final column in model.indexedColumns) {
      if (column.type == ColumnType.foreignKey) {
        final indexName = 'idx_${model.tableName}_${column.name}_id';
        buffer.writeln(
            'CREATE INDEX $indexName ON ${model.tableName} (${column.name}_id);');
      } else {
        final indexName = 'idx_${model.tableName}_${column.name}';
        buffer.writeln(
            'CREATE INDEX $indexName ON ${model.tableName} (${column.name});');
      }
    }

    // Generate custom indexes
    for (final index in model.indexes) {
      final indexType = index.isUnique ? 'UNIQUE INDEX' : 'INDEX';
      final columns = index.columns.join(', ');
      buffer.writeln(
          'CREATE $indexType ${index.name} ON ${model.tableName} ($columns);');
    }

    return buffer.toString().trim();
  }

  /// Convert string to snake_case
  String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(
            RegExp(r'[A-Z]'), (match) => '_${match.group(0)?.toLowerCase()}')
        .replaceFirst(RegExp(r'^_'), '');
  }

  /// Factory method to create generator from schema file
  static Future<CodeGenerator> fromSchemaFile({
    required String schemaPath,
    required String outputDirectory,
  }) async {
    print('📖 Loading schema from: $schemaPath');

    final schema = await SchemaDefinition.fromFile(schemaPath);

    print('   Found ${schema.models.length} models:');
    for (final model in schema.models) {
      print('     - ${model.name} (${model.columns.length} columns)');
    }

    return CodeGenerator(
      schema: schema,
      outputDirectory: outputDirectory,
    );
  }
}
