/// Model generator for Gisila ORM
/// 
/// Generates Dart model classes with CRUD operations, validation,
/// and relationship handling from schema definitions.
library gisila.generators.model_generator;

import 'dart:io';
import 'schema_parser.dart';

/// Model class generator
class ModelGenerator {
  final SchemaDefinition schema;
  final String outputDirectory;

  ModelGenerator({
    required this.schema,
    required this.outputDirectory,
  });

  /// Generate all model files
  Future<void> generateAll() async {
    // Create output directory
    final dir = Directory(outputDirectory);
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }

    // Generate individual model files
    for (final model in schema.models) {
      await _generateModelFile(model);
    }

    // Generate barrel file
    await _generateBarrelFile();

    // Generate base model
    await _generateBaseModel();

    // Generate database context
    await _generateDatabaseContext();
  }

  /// Generate a single model file
  Future<void> _generateModelFile(ModelDefinition model) async {
    final content = _generateModelClass(model);
    final fileName = '${_toSnakeCase(model.name)}.dart';
    final file = File('$outputDirectory/$fileName');
    await file.writeAsString(content);
  }

  /// Generate model class content
  String _generateModelClass(ModelDefinition model) {
    final buffer = StringBuffer();
    
    // File header
    buffer.writeln('/// Generated model class for ${model.name}');
    buffer.writeln('/// DO NOT EDIT - This file is automatically generated');
    buffer.writeln();
    
    // Imports
    buffer.writeln("import 'dart:async';");
    buffer.writeln("import 'package:pg_dorm/config/config.dart';");
    buffer.writeln("import '../database/postgres/query/query.dart';");
    buffer.writeln("import '../database/postgres/query/operator.dart';");
    buffer.writeln("import '../queries/${_toSnakeCase(model.name)}_query.dart';");
    buffer.writeln("import 'base_model.dart';");
    buffer.writeln("import 'database_context.dart';");
    
    // Import related models
    for (final column in model.columns) {
      if (column.isRelationship && column.relationship?.references != null) {
        final refModel = column.relationship!.references!;
        if (refModel != model.name) {
          buffer.writeln("import '${_toSnakeCase(refModel)}.dart';");
        }
      }
    }
    buffer.writeln();

    // Class definition
    buffer.writeln('class ${model.name} extends BaseModel {');
    
    // Properties
    buffer.writeln('  // Properties');
    for (final column in model.columns) {
      buffer.writeln('  ${column.dartType} ${column.name};');
    }
    buffer.writeln();

    // Constructor
    buffer.writeln('  // Constructor');
    buffer.writeln('  ${model.name}({');
    for (final column in model.columns) {
      if (column.constraints.isNull || column.constraints.defaultValue != null) {
        buffer.writeln('    this.${column.name},');
      } else {
        buffer.writeln('    required this.${column.name},');
      }
    }
    buffer.writeln('  });');
    buffer.writeln();

    // Table name
    buffer.writeln('  // Table information');
    buffer.writeln("  static const String tableName = '${model.tableName}';");
    buffer.writeln();

    // toMap method
    buffer.writeln('  // Serialization');
    buffer.writeln('  @override');
    buffer.writeln('  Map<String, dynamic> toMap() {');
    buffer.writeln('    return {');
    for (final column in model.columns) {
      if (!column.isRelationship) {
        buffer.writeln("      '${column.name}': ${column.name},");
      } else if (column.type == ColumnType.foreignKey) {
        buffer.writeln("      '${column.name}_id': ${column.name}?.id,");
      }
    }
    buffer.writeln('    };');
    buffer.writeln('  }');
    buffer.writeln();

    // fromMap method
    buffer.writeln('  // Deserialization');
    buffer.writeln('  factory ${model.name}.fromMap(Map<String, dynamic> map) {');
    buffer.writeln('    return ${model.name}(');
    for (final column in model.columns) {
      if (!column.isRelationship) {
        if (column.type == ColumnType.timestamp || column.type == ColumnType.date) {
          buffer.writeln("      ${column.name}: map['${column.name}'] != null ? DateTime.parse(map['${column.name}']) : null,");
        } else {
          buffer.writeln("      ${column.name}: map['${column.name}'] as ${column.dartType},");
        }
      }
    }
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln();

    // Validation
    buffer.writeln('  // Validation');
    buffer.writeln('  @override');
    buffer.writeln('  List<String> validate() {');
    buffer.writeln('    final errors = <String>[];');
    buffer.writeln();
    
    for (final column in model.columns.where((c) => !c.isRelationship)) {
      if (!column.constraints.isNull) {
        buffer.writeln('    if (${column.name} == null) {');
        buffer.writeln("      errors.add('${column.name} is required');");
        buffer.writeln('    }');
      }
      
      if (column.type == ColumnType.varchar && !column.constraints.allowBlank) {
        buffer.writeln('    if (${column.name} != null && ${column.name}!.trim().isEmpty) {');
        buffer.writeln("      errors.add('${column.name} cannot be blank');");
        buffer.writeln('    }');
      }
    }
    
    buffer.writeln();
    buffer.writeln('    return errors;');
    buffer.writeln('  }');
    buffer.writeln();

    // CRUD Operations - Create
    buffer.writeln('  // CRUD Operations');
    buffer.writeln('  static Future<${model.name}> create({');
    for (final column in model.columns.where((c) => !c.constraints.isPrimary && !c.isRelationship)) {
      if (column.constraints.isNull || column.constraints.defaultValue != null) {
        buffer.writeln('    ${column.dartType} ${column.name},');
      } else {
        buffer.writeln('    required ${column.dartType} ${column.name},');
      }
    }
    for (final column in model.foreignKeyColumns) {
      if (column.constraints.isNull) {
        buffer.writeln('    ${column.dartType} ${column.name},');
      } else {
        buffer.writeln('    required ${column.dartType} ${column.name},');
      }
    }
    buffer.writeln('    String? connectionName,');
    buffer.writeln('  }) async {');
    buffer.writeln('    final instance = ${model.name}(');
    for (final column in model.columns.where((c) => !c.constraints.isPrimary)) {
      if (!column.isRelationship) {
        buffer.writeln('      ${column.name}: ${column.name},');
      } else if (column.type == ColumnType.foreignKey) {
        buffer.writeln('      ${column.name}: ${column.name},');
      }
    }
    buffer.writeln('    );');
    buffer.writeln();
    buffer.writeln('    // Validate');
    buffer.writeln('    final validationErrors = instance.validate();');
    buffer.writeln('    if (validationErrors.isNotEmpty) {');
    buffer.writeln('      throw ValidationException(validationErrors);');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    // Execute insert');
    buffer.writeln('    final context = DatabaseContext.instance;');
    buffer.writeln('    final result = await context.insert(');
    buffer.writeln('      tableName: tableName,');
    buffer.writeln('      data: instance.toMap(),');
    buffer.writeln('      connectionName: connectionName,');
    buffer.writeln('    );');
    buffer.writeln();
    buffer.writeln('    instance.${model.primaryKey?.name ?? 'id'} = result[\'${model.primaryKey?.name ?? 'id'}\'] as ${model.primaryKey?.dartType ?? 'int'};');
    buffer.writeln('    return instance;');
    buffer.writeln('  }');
    buffer.writeln();

    // CRUD Operations - Find by ID
    buffer.writeln('  static Future<${model.name}?> findById(');
    buffer.writeln('    ${model.primaryKey?.dartType ?? 'int'} id, {');
    buffer.writeln('    String? connectionName,');
    buffer.writeln('  }) async {');
    buffer.writeln('    final context = DatabaseContext.instance;');
    buffer.writeln('    final results = await context.query(');
    buffer.writeln('      sql: \'SELECT * FROM \$tableName WHERE ${model.primaryKey?.name ?? 'id'} = ?\',');
    buffer.writeln('      parameters: [id],');
    buffer.writeln('      connectionName: connectionName,');
    buffer.writeln('    );');
    buffer.writeln();
    buffer.writeln('    if (results.isEmpty) return null;');
    buffer.writeln('    return ${model.name}.fromMap(results.first);');
    buffer.writeln('  }');
    buffer.writeln();

    // CRUD Operations - Find all
    buffer.writeln('  static Future<List<${model.name}>> findAll({');
    buffer.writeln('    String? where,');
    buffer.writeln('    List<dynamic>? parameters,');
    buffer.writeln('    String? orderBy,');
    buffer.writeln('    int? limit,');
    buffer.writeln('    int? offset,');
    buffer.writeln('    String? connectionName,');
    buffer.writeln('  }) async {');
    buffer.writeln('    final context = DatabaseContext.instance;');
    buffer.writeln('    final buffer = StringBuffer(\'SELECT * FROM \$tableName\');');
    buffer.writeln();
    buffer.writeln('    if (where != null) {');
    buffer.writeln('      buffer.write(\' WHERE \$where\');');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    if (orderBy != null) {');
    buffer.writeln('      buffer.write(\' ORDER BY \$orderBy\');');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    if (limit != null) {');
    buffer.writeln('      buffer.write(\' LIMIT \$limit\');');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    if (offset != null) {');
    buffer.writeln('      buffer.write(\' OFFSET \$offset\');');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    final results = await context.query(');
    buffer.writeln('      sql: buffer.toString(),');
    buffer.writeln('      parameters: parameters ?? [],');
    buffer.writeln('      connectionName: connectionName,');
    buffer.writeln('    );');
    buffer.writeln();
    buffer.writeln('    return results.map((row) => ${model.name}.fromMap(row)).toList();');
    buffer.writeln('  }');
    buffer.writeln();

    // CRUD Operations - Update
    buffer.writeln('  Future<bool> save({String? connectionName}) async {');
    buffer.writeln('    // Validate');
    buffer.writeln('    final validationErrors = validate();');
    buffer.writeln('    if (validationErrors.isNotEmpty) {');
    buffer.writeln('      throw ValidationException(validationErrors);');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    final context = DatabaseContext.instance;');
    buffer.writeln('    final affectedRows = await context.update(');
    buffer.writeln('      tableName: tableName,');
    buffer.writeln('      data: toMap(),');
    buffer.writeln('      where: \'${model.primaryKey?.name ?? 'id'} = ?\',');
    buffer.writeln('      parameters: [${model.primaryKey?.name ?? 'id'}],');
    buffer.writeln('      connectionName: connectionName,');
    buffer.writeln('    );');
    buffer.writeln();
    buffer.writeln('    return affectedRows > 0;');
    buffer.writeln('  }');
    buffer.writeln();

    // CRUD Operations - Delete
    buffer.writeln('  Future<bool> delete({String? connectionName}) async {');
    buffer.writeln('    final context = DatabaseContext.instance;');
    buffer.writeln('    final affectedRows = await context.delete(');
    buffer.writeln('      tableName: tableName,');
    buffer.writeln('      where: \'${model.primaryKey?.name ?? 'id'} = ?\',');
    buffer.writeln('      parameters: [${model.primaryKey?.name ?? 'id'}],');
    buffer.writeln('      connectionName: connectionName,');
    buffer.writeln('    );');
    buffer.writeln();
    buffer.writeln('    return affectedRows > 0;');
    buffer.writeln('  }');
    buffer.writeln();

    // Static delete
    buffer.writeln('  static Future<bool> deleteById(');
    buffer.writeln('    ${model.primaryKey?.dartType ?? 'int'} id, {');
    buffer.writeln('    String? connectionName,');
    buffer.writeln('  }) async {');
    buffer.writeln('    final context = DatabaseContext.instance;');
    buffer.writeln('    final affectedRows = await context.delete(');
    buffer.writeln('      tableName: tableName,');
    buffer.writeln('      where: \'${model.primaryKey?.name ?? 'id'} = ?\',');
    buffer.writeln('      parameters: [id],');
    buffer.writeln('      connectionName: connectionName,');
    buffer.writeln('    );');
    buffer.writeln();
    buffer.writeln('    return affectedRows > 0;');
    buffer.writeln('  }');
    buffer.writeln();

    // Relationship methods
    for (final column in model.foreignKeyColumns) {
      final refModel = column.relationship!.references!;
      buffer.writeln('  // Load ${column.name} relationship');
      buffer.writeln('  Future<${refModel}?> load${_toPascalCase(column.name)}({String? connectionName}) async {');
      buffer.writeln('    if (${column.name} != null) return ${column.name};');
      buffer.writeln('    if (${column.name}_id == null) return null;');
      buffer.writeln();
      buffer.writeln('    ${column.name} = await ${refModel}.findById(${column.name}_id!, connectionName: connectionName);');
      buffer.writeln('    return ${column.name};');
      buffer.writeln('  }');
      buffer.writeln();
    }

    // Many-to-many relationships
    for (final column in model.manyToManyColumns) {
      final refModel = column.relationship!.references!;
      buffer.writeln('  // Load ${column.name} many-to-many relationship');
      buffer.writeln('  Future<List<${refModel}>> load${_toPascalCase(column.name)}({String? connectionName}) async {');
      buffer.writeln('    final context = DatabaseContext.instance;');
      buffer.writeln('    final junctionTable = \'${_toSnakeCase(model.name)}_${_toSnakeCase(refModel)}\';');
      buffer.writeln('    final sql = \'\'\'');
      buffer.writeln('      SELECT r.* FROM ${_toSnakeCase(refModel)} r');
      buffer.writeln('      INNER JOIN \$junctionTable j ON j.${_toSnakeCase(refModel)}_id = r.id');
      buffer.writeln('      WHERE j.${_toSnakeCase(model.name)}_id = ?');
      buffer.writeln('    \'\'\';');
      buffer.writeln();
      buffer.writeln('    final results = await context.query(');
      buffer.writeln('      sql: sql,');
      buffer.writeln('      parameters: [${model.primaryKey?.name ?? 'id'}],');
      buffer.writeln('      connectionName: connectionName,');
      buffer.writeln('    );');
      buffer.writeln();
      buffer.writeln('    return results.map((row) => ${refModel}.fromMap(row)).toList();');
      buffer.writeln('  }');
      buffer.writeln();
    }

    // Query builder methods
    buffer.writeln('  /// Create a query builder for this model');
    buffer.writeln('  static ${model.name}Query query() => ${model.name}Query();');
    buffer.writeln();
    
    buffer.writeln('  /// Find records using query builder');
    buffer.writeln('  static Future<List<${model.name}>> where(');
    buffer.writeln('    Operation operation, {');
    buffer.writeln('    String? connectionName,');
    buffer.writeln('  }) async {');
    buffer.writeln('    final queryBuilder = ${model.name}Query().where(operation);');
    buffer.writeln('    final context = DatabaseContext.instance;');
    buffer.writeln('    final sql = queryBuilder.toString();');
    buffer.writeln('    ');
    buffer.writeln('    final results = await context.query(');
    buffer.writeln('      sql: sql,');
    buffer.writeln('      parameters: [],');
    buffer.writeln('      connectionName: connectionName,');
    buffer.writeln('    );');
    buffer.writeln('');
    buffer.writeln('    return results.map((row) => ${model.name}.fromMap(row)).toList();');
    buffer.writeln('  }');
    buffer.writeln();
    
    buffer.writeln('  /// Find first record matching query');
    buffer.writeln('  static Future<${model.name}?> firstWhere(');
    buffer.writeln('    Operation operation, {');
    buffer.writeln('    String? connectionName,');
    buffer.writeln('  }) async {');
    buffer.writeln('    final queryBuilder = ${model.name}Query().where(operation).limit(1);');
    buffer.writeln('    final context = DatabaseContext.instance;');
    buffer.writeln('    final sql = queryBuilder.toString();');
    buffer.writeln('    ');
    buffer.writeln('    final results = await context.query(');
    buffer.writeln('      sql: sql,');
    buffer.writeln('      parameters: [],');
    buffer.writeln('      connectionName: connectionName,');
    buffer.writeln('    );');
    buffer.writeln('');
    buffer.writeln('    return results.isNotEmpty ? ${model.name}.fromMap(results.first) : null;');
    buffer.writeln('  }');
    buffer.writeln();

    // toString method
    buffer.writeln('  @override');
    buffer.writeln('  String toString() {');
    buffer.writeln('    return \'${model.name}{${model.primaryKey?.name ?? 'id'}: \$${model.primaryKey?.name ?? 'id'}}\';');
    buffer.writeln('  }');
    buffer.writeln();

    // Close class
    buffer.writeln('}');
    buffer.writeln();

    // Validation exception
    buffer.writeln('class ValidationException implements Exception {');
    buffer.writeln('  final List<String> errors;');
    buffer.writeln('  ValidationException(this.errors);');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  String toString() => \'ValidationException: \${errors.join(", ")}\';');
    buffer.writeln('}');

    return buffer.toString();
  }

  /// Generate base model class
  Future<void> _generateBaseModel() async {
    final content = '''
/// Base model class for all generated models
/// DO NOT EDIT - This file is automatically generated

abstract class BaseModel {
  /// Convert model to map for database operations
  Map<String, dynamic> toMap();
  
  /// Validate model instance
  List<String> validate();
}
''';

    final file = File('$outputDirectory/base_model.dart');
    await file.writeAsString(content);
  }

  /// Generate database context
  Future<void> _generateDatabaseContext() async {
    final content = '''
/// Database context for executing queries
/// DO NOT EDIT - This file is automatically generated

import 'dart:async';
import 'package:pg_dorm/config/config.dart';

class DatabaseContext {
  static DatabaseContext? _instance;
  static DatabaseContext get instance => _instance ??= DatabaseContext._();
  
  DatabaseContext._();
  
  /// Execute a query and return results
  Future<List<Map<String, dynamic>>> query({
    required String sql,
    required List<dynamic> parameters,
    String? connectionName,
  }) async {
    // TODO: Implement actual database query execution
    // This is a placeholder that should be replaced with actual database driver
    throw UnimplementedError('Database query execution not implemented');
  }
  
  /// Insert a record and return the inserted row
  Future<Map<String, dynamic>> insert({
    required String tableName,
    required Map<String, dynamic> data,
    String? connectionName,
  }) async {
    // TODO: Implement actual database insert
    // This is a placeholder that should be replaced with actual database driver
    throw UnimplementedError('Database insert execution not implemented');
  }
  
  /// Update records and return affected row count
  Future<int> update({
    required String tableName,
    required Map<String, dynamic> data,
    required String where,
    required List<dynamic> parameters,
    String? connectionName,
  }) async {
    // TODO: Implement actual database update
    // This is a placeholder that should be replaced with actual database driver
    throw UnimplementedError('Database update execution not implemented');
  }
  
  /// Delete records and return affected row count
  Future<int> delete({
    required String tableName,
    required String where,
    required List<dynamic> parameters,
    String? connectionName,
  }) async {
    // TODO: Implement actual database delete
    // This is a placeholder that should be replaced with actual database driver
    throw UnimplementedError('Database delete execution not implemented');
  }
}
''';

    final file = File('$outputDirectory/database_context.dart');
    await file.writeAsString(content);
  }

  /// Generate barrel file
  Future<void> _generateBarrelFile() async {
    final buffer = StringBuffer();
    
    buffer.writeln('/// Generated models barrel file');
    buffer.writeln('/// DO NOT EDIT - This file is automatically generated');
    buffer.writeln();
    
    buffer.writeln("export 'base_model.dart';");
    buffer.writeln("export 'database_context.dart';");
    
    for (final model in schema.models) {
      buffer.writeln("export '${_toSnakeCase(model.name)}.dart';");
    }

    final file = File('$outputDirectory/models.dart');
    await file.writeAsString(buffer.toString());
  }

  /// Convert string to snake_case
  String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(RegExp(r'[A-Z]'), (match) => '_${match.group(0)?.toLowerCase()}')
        .replaceFirst(RegExp(r'^_'), '');
  }

  /// Convert string to PascalCase
  String _toPascalCase(String input) {
    return input.split('_')
        .map((word) => word.isEmpty ? '' : '${word[0].toUpperCase()}${word.substring(1)}')
        .join('');
  }
} 