/// Query generator for Gisila ORM
/// Generates type-safe query builders for models

import 'dart:async';
import 'schema_parser.dart';
import 'model_generator.dart';

/// Generates query classes for type-safe WHERE clauses
class QueryGenerator {
  
  /// Generate query builder class for a model
  String generateQueryClass(ModelDefinition model) {
    final buffer = StringBuffer();
    
    // Class declaration
    buffer.writeln('/// Query builder for ${model.name} model');
    buffer.writeln('class ${model.name}Query extends Query {');
    buffer.writeln('  ${model.name}Query() {');
    buffer.writeln('    table = \'${model.tableName}\';');
    buffer.writeln('    columns = [');
    for (final column in model.regularColumns) {
      buffer.writeln('      \'${column.name}\',');
    }
    buffer.writeln('    ];');
    buffer.writeln('  }');
    buffer.writeln();
    
    // Factory constructor for referenced queries (joins)
    buffer.writeln('  factory ${model.name}Query.referenced({required List<Join> joins}) =>');
    buffer.writeln('      ${model.name}Query().._joins.addAll(joins);');
    buffer.writeln();
    
    // Table name constant
    buffer.writeln('  static const table = \'${model.tableName}\';');
    buffer.writeln();
    
    // Generate column getters for each field
    for (final column in model.columns) {
      if (column.isRelationship && column.type == ColumnType.manyToMany) {
        continue; // Skip many-to-many for now
      }
      
      final columnType = _getColumnType(column);
      if (column.type == ColumnType.foreignKey) {
        // Foreign key relationship
        final refModel = column.relationship!.references!;
        buffer.writeln('  ${refModel}Query get ${column.name} => ${refModel}Query.referenced(');
        buffer.writeln('      joins: [Join(table: \'${_toSnakeCase(refModel)}\', from: \'${model.tableName}\', onn: \'${column.name}_id\')]);');
        buffer.writeln();
      } else {
        // Regular column
        buffer.writeln('  $columnType get ${column.name} => $columnType(');
        buffer.writeln('      column: \'${column.name}\',');
        buffer.writeln('      offtable: \'${model.tableName}\',');
        buffer.writeln('      depends: _joins);');
        buffer.writeln();
      }
    }
    
    // Private joins list
    buffer.writeln('  final _joins = <Join>[];');
    buffer.writeln();
    
    // Column names list
    buffer.writeln('  static List<String> get columns => <String>[');
    for (final column in model.columns) {
      buffer.writeln('    \'${column.name}\',');
    }
    buffer.writeln('  ];');
    buffer.writeln();
    
    // Where method for building queries
    buffer.writeln('  ${model.name}Query where(Operation operation) {');
    buffer.writeln('    return ${model.name}Query()..operation = operation;');
    buffer.writeln('  }');
    buffer.writeln();
    
    // Select specific columns
    buffer.writeln('  ${model.name}Query select(List<String> columns) {');
    buffer.writeln('    return ${model.name}Query()..columns = columns;');
    buffer.writeln('  }');
    buffer.writeln();
    
    buffer.writeln('}');
    
    return buffer.toString();
  }
  
  /// Generate all query classes for a schema
  String generateAllQueryClasses(SchemaDefinition schema) {
    final buffer = StringBuffer();
    
    // Imports
    buffer.writeln('/// Generated query classes for type-safe WHERE clauses');
    buffer.writeln('/// DO NOT EDIT - This file is automatically generated');
    buffer.writeln();
    buffer.writeln('import \'../database/postgres/query/query.dart\';');
    buffer.writeln('import \'../database/postgres/query/operator.dart\';');
    buffer.writeln();
    
    // Generate query class for each model
    for (final model in schema.models) {
      buffer.writeln(generateQueryClass(model));
      buffer.writeln();
    }
    
    return buffer.toString();
  }
  
  /// Get appropriate column type for query builder
  String _getColumnType(ColumnDefinition column) {
    switch (column.type) {
      case ColumnType.varchar:
      case ColumnType.text:
      case ColumnType.uuid:
        return 'TextColumn';
      case ColumnType.integer:
      case ColumnType.bigint:
      case ColumnType.decimal:
        return 'NumberColumn';
      case ColumnType.boolean:
        return 'BooleanColumn';
      case ColumnType.date:
      case ColumnType.timestamp:
        return 'DateTimeColumn';
      case ColumnType.json:
        return 'TextColumn'; // JSON stored as text
      case ColumnType.foreignKey:
        return 'NumberColumn'; // Foreign keys are typically integers
      case ColumnType.manyToMany:
        return 'TextColumn'; // Fallback
    }
  }
  
  /// Convert string to snake_case
  String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(RegExp(r'[A-Z]'), (match) => '_${match.group(0)?.toLowerCase()}')
        .replaceFirst(RegExp(r'^_'), '');
  }
}

 